---
defaultGroups:
    - name: users
      must_exist: true
      system: true
    - name: wheel
      must_exist: false
      system: true
    - audio
    - video
    - input
    - storage
    - lp
    - rfkill
    - sys
    - network
doAutologin:     false
sudoersGroup:    wheel
setRootPassword: true
doReusePassword: true
passwordRequirements:
    minLength: 4
allowWeakPasswords: false
allowWeakPasswordsDefault: false
user:
    shell: /usr/bin/fish
    forbidden_names: [ root, live, greeter, nobody, bin, daemon, mail, ftp, http, dbus, polkitd, rtkit, uuidd ]
    home_permissions: "o700"
hostname:
    location: EtcFile
    writeHostsFile: true
    template: "chiroptera"
    forbidden_names: [ localhost ]
presets:
    fullName:  { editable: true }
    loginName: { editable: true }
